# Generated by Django 6.0.2 on 2026-03-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor'), ('R', 'Receptionist'), ('A', 'Admin')], default='P', help_text='User role within the clinic system.', max_length=1),
        ),
    ]
